### ISSUE TITLE
Leia a PEP's da lang por favor

### ISSUE THREAD

**Issue by HeavenH** [mthbernardes/strutszeiro#1]
https://www.python.org/dev/peps/pep-0008/

**Comment by HeavenH** [comment]
https://www.python.org/dev/peps/pep-0020/

**Comment by HeavenH** [comment]
https://www.python.org/dev/peps/pep-0008/#imports

**Comment by Pedro-Souza** [comment]
Please: https://www.python.org/dev/peps/pep-0257/

**Comment by HeavenH** [comment]
https://www.python.org/dev/peps/pep-0537/

**Comment by Pedro-Souza** [comment]
PLEASE: https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by mthbernardes** [comment]
Fique a vontade para enviar um pull request ;)

**Comment by Pedro-Souza** [comment]
Foi apenas dicas. Mas se o código seguisse pelo menos a pep8 daria para mandar :(
